# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "PlumageUI"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"
#engines:
#    template:
#        template_toolkit:
#            PRE_CHOMP: 1

# Include backtraces in any error messages.
traces: 1
# error_template is not effective in the version of Dancer2 shipped with Ubuntu
# 14.04 due to https://github.com/PerlDancer/Dancer2/issues/565 , so the file
# is just present as 500.tt for now. We possibly want to handle other codes
# differently anyway, and may even move to using the on_route_exception hook.
